### ISSUE TITLE
[Bug] Invalid/Expired API key crashes the page

### ISSUE THREAD

**Issue by iqbalio** [visgl/react-google-maps#137]
### Description

If the API key is expired/wrong. Then the page crashes once we move away from the map page. It throws the following error

`Cannot read properties of undefined (reading 'remove')`

### Steps to Reproduce

https://codesandbox.io/p/sandbox/gracious-rain-slhtvx

1. Open the above sandbox and click on "Map" link
2. Map page will open and It will show "Oops! Something went wrong." as the API key is wrong.
3. Click on Home link to go back to home page
4. Click on Map again

Now after this If you move again to home page or any other route, It'll crash the page.

### Environment

- Library version: 0.4.1
- Google maps version: weekly
- Browser and Version: Chrome 120
- OS: Windows 11

**Comment by usefulthink** [comment]
This seems to be coming from the effect-cleanup for the `useMapsEvents` hook. 
Needs some further investigation. 

We should also implement the `window.gm_authFailure` callback in the API-loader so we can properly react to problems with the API-key.

**Comment by usefulthink** [comment]
Interesting:

https://github.com/visgl/react-google-maps/blob/69bade05004234c0777d92a3be541369ec438e7a/src/components/map/use-map-events.ts#L62-L77

For the error to happen, `listener` has to be `undefined`, which - at least according to the google maps docs can't happen. I verified that in the debugger and indeed there seems to be a situation where the `google.maps.Map` instance has an empty function instead of `addListener` which isn't documented anywhere. i'll try to replace that with `google.maps.events.addListener` to see if that is more reliable.

**Comment by usefulthink** [comment]
With #158 and #165 this should be taken care of. Will release a new Version later today.
