### ISSUE TITLE
[Feat] Load Google Maps API Async

### ISSUE THREAD

**Issue by elliotwestlake** [visgl/react-google-maps#190]
### Target Use Case

When you load a map you get the following warning in the console: 
```
Google Maps JavaScript API has been loaded directly without loading=async.
```

### Proposal

Use `@googlemaps/react-wrapper` instead of custom wrapper

**Comment by usefulthink** [comment]
Interesting.. That seems to be a very new parameter they added, they didn't even update the documentation (or their own bootstrap-loader) to include that parameter yet: https://developers.google.com/maps/documentation/javascript/overview#bootstrap_loader

Regarding `@googlemaps/react-wrapper`: that package is incompatible with how we are loading the maps library and is likely going to be retired in favour of this library. The package that actually does the API loading would be `@googlemaps/js-api-loader` (which doesn't implement the `loading=async` flag either). The problem with that package is that it's a bit of a mix and match between the old way to load the maps API and the newer version (`google.maps.importLibrary`) that would introduce some unneeded overhead in our library.

That being said, we'll just add that parameter and we'll be fine :D

**Comment by usefulthink** [comment]
That loading-parameter was indeed added with v3.55 released this week: https://developers.google.com/maps/documentation/javascript/load-maps-js-api#optional_parameters_direct

**Comment by usefulthink** [comment]
fixed in https://github.com/visgl/react-google-maps/commit/cb1336fc97dda8b3ad99c3f9a9a560cf8186056b (v0.5.3)

**Comment by chrisjshull** [comment]
@usefulthink FYI, the Dynamic Library Import doesn't need the param (we can safely automatically infer it), but the direct script loading tag does need it done manually for backwards compatibility reasons. 

I might suggest using the https://www.npmjs.com/package/@googlemaps/js-api-loader instead of rolling a custom loader-builder (internally it uses the Dynamic Library Import).

**Comment by usefulthink** [comment]
@chrisjshull [our api-loader](https://github.com/visgl/react-google-maps/blob/1a9deb0d27abad0569a6b943c7d0a38d824e334c/src/libraries/google-maps-api-loader.ts#L93-L162) is really just an adjusted version (formatted, variables inlined and renamed, typescript, added handling of `nonce` and `gm_authFailure` and integration with our load-state handling) of the inline-script loader from [the official docs](https://developers.google.com/maps/documentation/javascript/load-maps-js-api). So it uses the same behavior, that is, declares an async `window.google.maps.importLibrary` function that will load the core-api to replace itself when first called.

We didn't add the @googlemaps/js-api-loader as dependecy since it seemed unnecessarily big, since all we needed was the dynamic loader. Interestingly, that is a similar approach as found in the [extended webcomponents repo](https://github.com/googlemaps/extended-component-library/blob/main/src/api_loader/inline_script.ts)).

I was thinking about proposing a 2.0 version for `@googlemaps/js-api-loader` that removes the legacy functions and most of the overhead and essentially just provides an npm version of the dynamic loader. Would you be in support of that?

**Comment by chrisjshull** [comment]
I would support that 👍
