### ISSUE TITLE
Map does not display unless width and height are specified

### ISSUE THREAD

**Issue by ghferrari** [visgl/react-google-maps#234]
### Description

I created a brand new React project using Vite via:
```
npm create vite@latest
```
After installing the `@vis-gl/react-google-maps` package, I tried to follow the basic usage example, adding the suggested code (copied below) to my `app.tsx` file.
```
import {APIProvider, Map, Marker} from '@vis.gl/react-google-maps';

function App() {
  const position = {lat: 53.54992, lng: 10.00678};

  return (
    <APIProvider apiKey={'YOUR API KEY HERE'}>
      <Map defaultCenter={position} defaultZoom={10}>
        <Marker position={position} />
      </Map>
    </APIProvider>
  );
}

export default App;
```

The result is that no map is displayed, unless one manually sets a width and height on the map either directly via the `style`, e.g.
```
<Map defaultCenter={position} defaultZoom={3}
      style={{width: "400px", height: "400px"}}
    >
```
or alternatively using e.g. using TailwindCSS classes
```
<Map defaultCenter={position} defaultZoom={3}
      className="w-[400px] h-[400px]"
    >
```

I don't know if you would consider this a bug, but at the very least, the documentation and suggested example should make it explicit that one must set a width/height on the map before it will display.

### Steps to Reproduce

See above

### Environment

@vis-gl/google-maps-react 0.70

**Comment by usefulthink** [comment]
Fully agree that this is a documentation fix we should make. If there are any takers, this should be mentioned in the topmost section of [./docs/api-reference/components/map.md](https://github.com/visgl/react-google-maps/blob/main/docs/api-reference/components/map.md).

The way this works is that if no `className` is specified for the Map component, the map will default to `width: 100%; height: 100%`, which requires the parent element to have a non-zero size (this probably isn't the case for you). When you specify a class, the default styles are removed since we don't want to interfere with whatever sizing is chosen there. Besides that, you can of courwse also override the style with whatever size you want.

**Comment by fzkhan19** [comment]
I'll pick up this issue

**Comment by usefulthink** [comment]
I already added a bit to the documentation in this commit: https://github.com/visgl/react-google-maps/pull/242/commits/0fe174aefe5e765ad90a09d1dcfabf838eecd75e – do you think that'd be enough or do you want to expand on that?

**Comment by ghferrari** [comment]
Updating the API reference docs is very useful. But I think the main thing is to make sure that the first example code in `README.md` (i.e. the first example under `Usage`) actually works  - perhaps by adding a surrounding div with width and height specified.

**Comment by fzkhan19** [comment]
@usefulthink That's perfect.

**Comment by usefulthink** [comment]
See also #265.
