### ISSUE TITLE
[Bug] Using AdvancedMarker will not update position using real time traking

### ISSUE THREAD

**Issue by mariushincu7** [visgl/react-google-maps#248]
### Description

I have a Markers component where I render all of my drivers positions using AdvancedMarker but the position is never updated. If I use Marker component exported from library it will update every time when new location is received

### Steps to Reproduce

Create a AdvancedMarker component and update the position at a certain interval then replace the component with Marker and see the difference

```
export const Markers = ({ points }) => {
  return (
    <>
      {points.map((point) => (
        <AdvancedMarker position={point} key={point.id_driver}>
          <Image
            src="/assets/car_top.png"
            width={35}
            height={50}
            style={{
              transform: `translate(-50%, -50%) rotate(${point.bearing}deg)`,
              position: "absolute",
              top: "50%",
              left: "50%",
              transition: "all 1s ease",
            }}
            alt="car"
          />
        </AdvancedMarker>
      ))}
    </>
  );
};
```

### Environment

- Library version: 0.7.1
- Google maps version: latest
- Browser and Version: Chrome 122.0.6261.94
- OS: Mac

**Comment by mrMetalWood** [comment]
Hi @mariushincu7, thanks for reporting the issue.

I tried to reproduce it with a minimal example and it seems to be working as expected for me. 
[https://stackblitz.com/edit/vitejs-vite-p7w444?file=src%2Fmain.tsx](https://stackblitz.com/edit/vitejs-vite-p7w444?file=src%2Fmain.tsx)
One of the markers in the example is a `Marker`, the other one an `AdvancedMarker`.

 Could you try to provide a minimal running example on codesandbox or stackblitz where the bug is happening so we can investigate what might be causing this behaviour for you?

**Comment by mariushincu7** [comment]
Something odd this time. Seem to work fine and moving the markers sorry for bothering.
