### ISSUE TITLE
Add a hook to update the local

### ISSUE THREAD

**Issue by LucasReyre** [visgl/react-google-maps#317]
### Target Use Case

I'm using next-intl to manage locale and internationalization on my site.
When changing the locale the context is not update as mentionned in the documentation.
And I get the following warning:
![image](https://github.com/visgl/react-google-maps/assets/6523353/99a15512-d74d-4f62-91ca-a7b714901a26)

### Proposal

Add a hook to update the local

**Comment by usefulthink** [comment]
Yeah, I'd love that as well, but unfortunately that is an issue you have to take to the google maps team: https://issuetracker.google.com/issues/35819089 – it's just not possible to change the locale once the API is loaded. We initially planned to reload the entire API when the language/region settings are changed, but this is also no longer possible since the Maps API started to use web-components (web-components can't be unregistered or changed once they have been registered for a document, and reloading the API would try to do that).

**Comment by LucasReyre** [comment]
Thanks for the explanation.
Do you have a workaround other than refresh the page? 
I ll go with the default browser language otherwise :/
