### ISSUE TITLE
Use the API libraries without the need of using a map first [Feat]

### ISSUE THREAD

**Issue by benshabatnoam** [visgl/react-google-maps#331]
### Target Use Case

We want to be able to use the google map libraries without wrapping our component inside a map as we don't need one.
We want to use the Gecoding class in order to get lat and long for some random address.

### Proposal

Currently the `useMapsLibrary('geocoding')` will work only if our component is wrapped with a `APIProvider` and `Map` components.
Can't we just use this hook without a `APIProvider` and `Map` component wrappers?
Thanks!

**Comment by usefulthink** [comment]
You can't use it without the `APIProvider`, but you should be able to use it without a `Map`. If that's not the case it would definitely be a bug.

The APIProvider is needed since that is the component that handles loading the maps-API (in the current implementation that is essentially setting up the `google.maps.importLibrary` function that is needed for the `useMapsLibrary` hook). We will always load the `core` and `maps` libraries of the google maps API, but that is likely not making a difference, since those will be dependencies for everything else.

**Comment by benshabatnoam** [comment]
I agree, using the `APIProvider` make sense.
(Still I suggest you guys update [this doc](https://github.com/visgl/react-google-maps#using-other-libraries-of-the-maps-javascript-api) as it's not 100% clear from it that one should use the `APIProvider` to use that hook)

As for the `Map` wrapper, I'm pretty sure that I needed it as well, I'll double check that and if so I'll try to make a small demo to demonstrate that.

Thanks a lot.

**Comment by usefulthink** [comment]
Works as expected: https://codesandbox.io/p/devbox/vigorous-mahavira-dmmxwk?file=%2Fsrc%2Fapp.tsx%3A16%2C28

**Comment by usefulthink** [comment]
updated README: https://github.com/visgl/react-google-maps/pull/332/

**Comment by benshabatnoam** [comment]
> Works as expected: https://codesandbox.io/p/devbox/vigorous-mahavira-dmmxwk?file=%2Fsrc%2Fapp.tsx%3A16%2C28

Yes for me as well...
