### ISSUE TITLE
[Feat] Change the language

### ISSUE THREAD

**Issue by pondz1** [visgl/react-google-maps#400]
### Target Use Case

Easy to change language

### Proposal

Makes it possible to change the language without having to reload the page.

**Comment by usefulthink** [comment]
I'd love to be able to do this, but it's impossible at the moment. The best you can do is to not set the language, in which case the maps API will use the locale settings of the user-agent.

Background: For a variety of reasons, the language has to be set when loading the Maps JavaScript API, which is handled by our `APIProvider`. I initially had an implementation that allowed unloading and reloading the entire Maps API, but that doesn't work anymore since the API also registers web-components that can't be unregistered or re-registered, so if you load the API a second time, it will just fail.

There is an [open issue in the Google Maps Platform Issue Tracker](https://issuetracker.google.com/issues/35819089), but that has been around for a while, so I wouldn't hold my breath. Still, adding a +1 and maybe a comment on that won't hurt.
