### ISSUE TITLE
[Bug] Infinite loop using AdvancedMarkers when the marker items are changed

### ISSUE THREAD

**Issue by galaxxy22** [visgl/react-google-maps#409]
### Description

I am filtering the markers to show on the map, this works the first time when enabling a filter. But once disabling the filter, I get a "Maximum update depth exceeded" error. The problem seems to be something in the setMarkerRef function

### Steps to Reproduce

```tsx
import React, { useEffect, useRef, useState } from "react";
import { MarkerClusterer } from "@googlemaps/markerclusterer";
import { AdvancedMarker, useMap } from "@vis.gl/react-google-maps";

const Markers = ({ points, activeMarkersCallback }) => {
	const map = useMap();
	const [markers, setMarkers] = useState({});
	const clusterer = useRef(null);

	useEffect(() => {
		if (!map || !points) return;

		if (!clusterer.current) {
			clusterer.current = new MarkerClusterer({
				map,
				renderer: {
					render: ({ count, position }) => {
						return new google.maps.Marker({
							position,
							icon: {
								url: '/images/content/marker.png',
								scaledSize: new google.maps.Size(32, 32),
								origin: new google.maps.Point(0, 0),
								anchor: new google.maps.Point(16, 16),
								labelOrigin: new google.maps.Point(16, 16)
							},
							label: {
								text: count.toString(),
								color: '#1E4844',
								fontWeight: '500',
								fontSize: '16px'
							},
							zIndex: 1000 + count
						});
					}
				},
				onClusterClick: handleClusterClick
			});
		}
	}, [map, points]);

	// Update markers
	useEffect(() => {
		if (!clusterer.current) return;
		clusterer.current?.clearMarkers();
		clusterer.current?.addMarkers(Object.values(markers));
	}, [markers]);

	const handleClusterClick = (event, cluster, map) => {
		const list = [];
		cluster.markers.forEach((marker) => {
			const tempDiv = document.createElement('div');
			tempDiv.innerHTML = marker.gx.innerHTML;
			const spanElement = tempDiv.querySelector('span[id]');
			const idValue = spanElement ? spanElement.id : null;
			list.push(idValue);
		});
		activeMarkersCallback(list);
	};

	const setMarkerRef = (marker, key) => {
		if (marker && markers[key]) return;
		if (!marker && !markers[key]) return;

		setMarkers(prev => {
			if (marker) {
				return { ...prev, [key]: marker };
			} else {
				const newMarkers = { ...prev };
				delete newMarkers[key];
				return newMarkers;
			}
		});
	};

	return (
		<>
			{points.map((point) => {
				return (
					<AdvancedMarker
						key={point.id}
						id={point.id}
						position={{ lat: point.latitude, lng: point.longitude }}
						ref={marker => setMarkerRef(marker, point.id)}
						onClick={() => activeMarkersCallback([point.id])}
						title={point.title}

					>
						<span id={point.id} className="maps_marker">1</span>
					</AdvancedMarker>
				)

			})}
		</>
	);
};

export default Markers;
```

Filter the points coming in via the props and disable the filter again: https://gyazo.com/e6c656d16796abcbb02a21425279d594

### Environment

- Library version: 1.0.2
- Google maps version: weekly
- Browser and Version: Chrome, latest
- OS: Windows

**Comment by usefulthink** [comment]
Just a quick first impression: when rendering the AdvancedMarkers, the values of the `position`, `ref` and `onClick` props are not memoized. This means they will have a different value every time the `Markers` component is rendered, which in turn will cause the AdvancedMarker components to re-render as well. 

Next, once the ref of the marker resolves (the ref callback and thus `setMarkerRef` is called), this will inevitably cause an update to the state within the `Markers` component, and as such trigger a re-render. And here, since the ref-component has a new callback as value, it will get called by React, completing the infinite loop.

I think just memoizing that ref-value will likely already solve that problem.

On an unrelated note: I'm not sure what you're doing in the `handleClusterClick` function, but accessing internal fields of Maps API objects (like `marker.gx`) will typically break with every release of the API since the names assigned to them a somewhat randomized at build time.

**Comment by galaxxy22** [comment]
Thank you! This indeed seems to fix it. And yes the handleClusterClick is temporairy, still need to fix this.
