### ISSUE TITLE
Unable to remove scrollbar from InfoWindow.

### ISSUE THREAD

**Issue by josh-thompson13** [visgl/react-google-maps#473]
### Description

I am unable to remove the scrollbar seen in the image attached. If I remove the overflow-scroll from the dom directly it disappears. Here is the code:

```
<InfoWindow
                                position={{ lat: 40, lng: 0 }}
                                // maxWidth={100}
                                // style={{ overflow: "hidden !important" }}
                                className="overflow-hidden-important"
                            >
                                <p className="h-full w-full">
                                    This is the content for another infowindow with <em>HTML</em>
                                    -elements.
                                </p>
                            </InfoWindow>
```

Is there anyway I can forcefully override this. The problematic div has a className of "gm-style-iw-d". 

![Screenshot 2024-08-08 at 9 15 55 AM](https://github.com/user-attachments/assets/4bed379a-2302-4a23-9434-367c2883cb33)

### Steps to Reproduce

See description.

### Environment

- Library version: 1.1.0
- Google maps version: weekly
- Browser and Version: Chrome
- OS: Mac OS

**Comment by mrMetalWood** [comment]
Interesting 🤔 I tried to reproduce the issue here:
https://codesandbox.io/p/devbox/info-window-scrollbars-fntrqf?file=%2Fsrc%2Fapp.tsx%3A11%2C32&workspaceId=308f8424-7fda-45b9-be07-d27ae10b961b

Do you see scroll bars here as well? This is what it looks for me. 

![Screenshot 2024-08-08 at 12 38 26](https://github.com/user-attachments/assets/a3546f65-e312-4693-88ff-66d89d37cf68)

But then again I see this in the CSS.

<img width="1010" alt="Screenshot 2024-08-08 at 12 38 20" src="https://github.com/user-attachments/assets/6b641022-dc28-4b5a-a208-c71a3eb4ce1e">

Looks like the Google Maps API overwrites itself from `overflow: auto` (which makes sense) to `overflow: scroll` with inline styles (which does not make sense to me why it should do that).
