### ISSUE TITLE
mapTypeId change is not working

### ISSUE THREAD

**Issue by padawannn** [visgl/react-google-maps#9]
This issue is very similar to [this one](https://github.com/visgl/react-google-maps/issues/4)  but in this case the library doesn't detect a mapTypeId change. I mean, if you keep the same `mapId` but you change the `mapTypeId` the map is not reloaded

**Comment by pauljnoble** [comment]
Not sure if changing `mapTypeId` is permitted with Cloud styled maps? See https://issuetracker.google.com/161501609 and https://stackoverflow.com/questions/62780394/how-do-i-change-the-mapid-of-a-google-vector-map

**Comment by usefulthink** [comment]
Yeah, that might unfortunately be true. But we still have the option to reload the map-instance in that case. I'm just testing it myself, will report back...

**Comment by padawannn** [comment]
> I don't think `mapTypeId` can be changed dynamically with Cloud styled maps.
> 
> See https://issuetracker.google.com/161501609 and https://stackoverflow.com/questions/62780394/how-do-i-change-the-mapid-of-a-google-vector-map

Is the same case as `mapId ` you can change it dynamically creating a new instance of the map as @usefulthink says

**Comment by usefulthink** [comment]
I updated [the example here](https://visgl.github.io/react-google-maps/examples/change-map-id) and I'd say this is behaving exactly as expected. When the `mapId` is changed along with the `mapTypeId` the map will reload (due to the `mapId` change), but if you change only the `mapTypeId`, the changes happens instantly.

Is there anything wrong with that? Or where do you see a problem here?

**Comment by usefulthink** [comment]
That wasn't even any change in the code, but I published a new version a couple hours ago.
