### ISSUE TITLE
[Bug] changing the center coordinates doesn't reposition the map

### ISSUE THREAD

**Issue by BhaskaranR** [visgl/react-google-maps#96]
### Description

Changing the coordinates by selecting different place doesn't reposition the map. new markers are added but the position of map stays as is.

### Steps to Reproduce

```
  const [zoomLevel, setZoomLevel] = useState(12);
  const map = useMap();
  const [coords] = useState<Coordinates>(selectedCoords);

 return ( <APIProvider apiKey={env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}>
      <div style={{ height: "90vh", width: "100%" }}>
        <Map
          center={coords}
          zoom={zoomLevel}
          disableDefaultUI={false}
          clickableIcons={true}
          mapId={process.env.NEXT_PUBLIC_MAP_ID}
        />
    </div>
)
```

### Environment

- Library version:
- Google maps version: weekly
- Browser and Version: chrome
- OS: mac

**Comment by usefulthink** [comment]
to reproduce: https://codesandbox.io/p/devbox/flamboyant-hermann-vlgj59

**Comment by sosualfred** [comment]
@usefulthink The example above explicitly sets the position. I think the issue occurs when you drag the map and try to recenter via a state variable. Nothing happens because the state variable is not changed via onCenterChanged.

**Comment by usefulthink** [comment]
Oh, so you mean re-centering the map to the point that is already in the `center` prop?

**Comment by sosualfred** [comment]
💯 If the center prop has not changed and you try to re-center it won't work. Adding that to the Docs will help prevent future pitfalls.

**Comment by BhaskaranR** [comment]
in my case center prop did change. map UI wont recenter.

**Comment by usefulthink** [comment]
What @sosualfred suggested above is the best solution to this I'd think.

The problem arises in this part of the code that is responsible for updating the map when the `center`-prop changes:

https://github.com/visgl/react-google-maps/blob/1dc158436c4ffde60548486da5410b46e989fc5b/src/components/map/use-map-options.ts#L53-L62

As you can see, the repositioning of the map depends on the `lat` and `lng` values, not on the `center` object.
The reason for this is a bit further up:

https://github.com/visgl/react-google-maps/blob/1dc158436c4ffde60548486da5410b46e989fc5b/src/components/map/use-map-options.ts#L22-L29

Since `center` can be specified as `google.maps.LatLng`, we have to convert it to `google.maps.LatLngLiteral` to be consistent internally. So when it's specified as `google.maps.LatLng` we would otherwise constantly update the camera.
At this point it might be worth to also consider removing support for the `google.maps.LatLng` type and friends, it's not like they have any notable benefits and if users choose to use them for whatever reason, they can always be easily converted to the LatLngLiteral format.

**Comment by BhaskaranR** [comment]
this is no longer a issue. thanks for the help

**Comment by perrywink** [comment]
I could be doing something incorrectly, but as of now it seems that this issues has resurfaced. Below, I am using it in conjunction with a result passed in as a prop:
- "placeSelected" is a state from the parent component
- I have verified that position updates correctly. However, it seems I need to do the additional `map.moveCamera` in order for the map to recenter.
- This is in a Next 14 Project

```
"use client"
import { Map, Marker, useMap } from '@vis.gl/react-google-maps';
import { useMapStyles } from './map-styles';
import { useEffect, useState } from 'react';

interface Props {
  placeSelected: google.maps.places.PlaceResult | null
}

export function GoogleMap({placeSelected}: Props) {
  const defaultPos: google.maps.LatLngLiteral = {
    lat: -37.840935,
    lng: 144.946457
  };
  const [center, setCenter] = useState<google.maps.LatLngLiteral>(defaultPos)
  const map = useMap();

  useEffect(() => {
    if (!placeSelected) return;
    
    const newPos: google.maps.LatLngLiteral = {
      lat: placeSelected?.geometry?.location?.lat()!,
      lng: placeSelected?.geometry?.location?.lng()!
    };
    setCenter(newPos)

    // a manual move should not be neccesary. need to investigate.
    map?.moveCamera({
      center: newPos
    })
  }, [placeSelected])

  return (
    <Map 
      defaultCenter={center} 
      defaultZoom={13} 
      styles={useMapStyles()} 
      className='w-full' 
      disableDefaultUI
    >
      {
        placeSelected && (
          <Marker position={{
            lat: placeSelected.geometry?.location?.lat()!,
            lng: placeSelected.geometry?.location?.lng()!,
          }}/>
        )
      }
    </Map>
  );
}

```
